version: '3.7'

services:
  Portainer:
    image: 192.168.1.147:443/docker
    command: "docker run --rm --name wago-portainer -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data 192.168.1.147:443/portainer-ce"
    networks:
      - bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

networks:
  bridge:
    external: true
    name: bridge
